services:
  - type: web
    name: shastra-backend
    env: docker
    dockerContext: crime_backend/MODULE_2_BACKEND
    dockerfilePath: crime_backend/MODULE_2_BACKEND/Dockerfile
    envVars:
      - key: PORT
        value: 8000
      - key: BACKEND_PORT
        value: 8000
      - key: ENVIRONMENT
        value: production
      - key: COOKIE_SAMESITE
        value: none
      - key: FRONTEND_URL
        value: https://shastra-60076818156.development.catalystserverless.in


