services:
  - type: web
    name: shastra-backend
    env: docker
    dockerContext: crime_backend/MODULE_2_BACKEND
    dockerfilePath: crime_backend/MODULE_2_BACKEND/Dockerfile
    envVars:
      - key: PORT
        value: 8000
      - key: ENVIRONMENT
        value: production
      - key: COOKIE_SAMESITE
        value: none

  - type: worker
    name: shastra-scheduler
    env: docker
    dockerContext: crime_backend/MODULE_2_BACKEND
    dockerfilePath: crime_backend/MODULE_2_BACKEND/Dockerfile.scheduler
    envVars:
      - key: ENVIRONMENT
        value: production
