// Complete mock data for all API endpoints

export const mockAuthResponse = {
  auth_token: "mock-jwt-token-12345",
  user_role: "SCRB Officer",
  user_name: "Suresh Kumar",
  user_district: "Bengaluru Urban",
  permissions_list: ["view_all", "edit_cases", "manage_users", "view_reports"],
};

export const mockDashboardSummary = {
  total_crimes_month: 2847,
  active_hotspots_count: 23,
  high_risk_areas_count: 8,
  repeat_offenders_count: 156,
  pending_alerts_count: 34,
  cases_solved_month: 412,
  total_crimes_trend: "+5.2%",
  hotspots_trend: "-2.1%",
  high_risk_trend: "+1.3%",
  offenders_trend: "+3.7%",
};

export const mockCrimeTrends = [
  { month: "Jan", crimes: 2100, solved: 380 },
  { month: "Feb", crimes: 1950, solved: 360 },
  { month: "Mar", crimes: 2300, solved: 420 },
  { month: "Apr", crimes: 2450, solved: 390 },
  { month: "May", crimes: 2200, solved: 410 },
  { month: "Jun", crimes: 2600, solved: 450 },
  { month: "Jul", crimes: 2750, solved: 480 },
  { month: "Aug", crimes: 2400, solved: 400 },
  { month: "Sep", crimes: 2650, solved: 430 },
  { month: "Oct", crimes: 2800, solved: 460 },
  { month: "Nov", crimes: 2700, solved: 440 },
  { month: "Dec", crimes: 2847, solved: 412 },
];

export const mockCrimeTypeBreakdown = [
  { type: "Theft", count: 842, percentage: 29.6 },
  { type: "Assault", count: 521, percentage: 18.3 },
  { type: "Robbery", count: 387, percentage: 13.6 },
  { type: "Fraud", count: 312, percentage: 11.0 },
  { type: "Burglary", count: 267, percentage: 9.4 },
  { type: "Drug Offense", count: 198, percentage: 7.0 },
  { type: "Vehicle Theft", count: 176, percentage: 6.2 },
  { type: "Murder", count: 87, percentage: 3.1 },
  { type: "Other", count: 57, percentage: 2.0 },
];

export const mockDistrictCrimeCounts = [
  { district: "Bengaluru Urban", count: 1247 },
  { district: "Mysuru", count: 342 },
  { district: "Kalaburagi", count: 287 },
  { district: "Belagavi", count: 265 },
  { district: "Ballari", count: 198 },
  { district: "Davanagere", count: 167 },
  { district: "Dharwad", count: 143 },
  { district: "Shivamogga", count: 132 },
];

export const mockRecentAlerts = [
  {
    alert_id: "ALT001",
    alert_type: "Crime Spike",
    severity: "Critical",
    location: "Whitefield, Bengaluru",
    district: "Bengaluru Urban",
    datetime: "2024-12-15T14:23:00",
    description: "Sudden 340% spike in vehicle theft incidents detected in Whitefield area",
    is_read: false,
    related_entity_id: "HS001",
    related_entity_type: "hotspot",
  },
  {
    alert_id: "ALT002",
    alert_type: "Known Criminal Spotted",
    severity: "High",
    location: "Shivajinagar, Bengaluru",
    district: "Bengaluru Urban",
    datetime: "2024-12-15T13:45:00",
    description: "High-risk offender Rajan Mehta (ID: OFF003) spotted near bank premises",
    is_read: false,
    related_entity_id: "OFF003",
    related_entity_type: "offender",
  },
  {
    alert_id: "ALT003",
    alert_type: "New Hotspot Emerging",
    severity: "High",
    location: "Kalaburagi Central",
    district: "Kalaburagi",
    datetime: "2024-12-15T12:30:00",
    description: "New criminal hotspot emerging in Kalaburagi Central market area",
    is_read: true,
    related_entity_id: "HS007",
    related_entity_type: "hotspot",
  },
  {
    alert_id: "ALT004",
    alert_type: "Anomaly Detected",
    severity: "Medium",
    location: "Mysuru Palace Area",
    district: "Mysuru",
    datetime: "2024-12-15T11:15:00",
    description: "Unusual pattern of fraud cases detected near tourist areas in Mysuru",
    is_read: true,
    related_entity_id: "ANO004",
    related_entity_type: "anomaly",
  },
  {
    alert_id: "ALT005",
    alert_type: "Prediction Threshold Breached",
    severity: "Medium",
    location: "Ballari Mining Belt",
    district: "Ballari",
    datetime: "2024-12-15T10:00:00",
    description: "AI prediction model indicates 87% probability of major crime event within 72 hours",
    is_read: true,
    related_entity_id: "PRD001",
    related_entity_type: "prediction",
  },
  {
    alert_id: "ALT006",
    alert_type: "Network Connection Discovered",
    severity: "High",
    location: "Multiple Locations",
    district: "Bengaluru Urban",
    datetime: "2024-12-14T22:30:00",
    description: "Criminal network linkage discovered between 3 previously unconnected cases",
    is_read: false,
    related_entity_id: "NET001",
    related_entity_type: "network",
  },
  {
    alert_id: "ALT007",
    alert_type: "Crime Spike",
    severity: "Low",
    location: "Raichur Town",
    district: "Raichur",
    datetime: "2024-12-14T20:15:00",
    description: "Moderate increase in drug-related offenses in Raichur town center",
    is_read: true,
    related_entity_id: "HS012",
    related_entity_type: "hotspot",
  },
  {
    alert_id: "ALT008",
    alert_type: "Anomaly Detected",
    severity: "Critical",
    location: "Belagavi Border",
    district: "Belagavi",
    datetime: "2024-12-14T18:45:00",
    description: "Suspected organized smuggling ring activity detected at Belagavi border checkpoints",
    is_read: false,
    related_entity_id: "ANO002",
    related_entity_type: "anomaly",
  },
];

export const mockRecentCrimes = [
  {
    crime_id: "CRM001",
    crime_type: "Vehicle Theft",
    date_time: "2024-12-15T14:10:00",
    location: "MG Road, Bengaluru",
    district: "Bengaluru Urban",
    police_station: "Cubbon Park PS",
    status: "Under Investigation",
    latitude: 12.9752,
    longitude: 77.6088,
  },
  {
    crime_id: "CRM002",
    crime_type: "Robbery",
    date_time: "2024-12-15T13:22:00",
    location: "Brigade Road, Bengaluru",
    district: "Bengaluru Urban",
    police_station: "Shivajinagar PS",
    status: "FIR Filed",
    latitude: 12.9716,
    longitude: 77.6099,
  },
  {
    crime_id: "CRM003",
    crime_type: "Assault",
    date_time: "2024-12-15T12:45:00",
    location: "Mysuru City Center",
    district: "Mysuru",
    police_station: "Mysuru Central PS",
    status: "Arrested",
    latitude: 12.2958,
    longitude: 76.6394,
  },
  {
    crime_id: "CRM004",
    crime_type: "Fraud",
    date_time: "2024-12-15T11:30:00",
    location: "Jayanagar, Bengaluru",
    district: "Bengaluru Urban",
    police_station: "Jayanagar PS",
    status: "Under Investigation",
    latitude: 12.9250,
    longitude: 77.5938,
  },
  {
    crime_id: "CRM005",
    crime_type: "Burglary",
    date_time: "2024-12-15T09:15:00",
    location: "Hubli Commercial Area",
    district: "Dharwad",
    police_station: "Hubli PS",
    status: "FIR Filed",
    latitude: 15.3647,
    longitude: 75.1240,
  },
  {
    crime_id: "CRM006",
    crime_type: "Drug Offense",
    date_time: "2024-12-15T08:00:00",
    location: "Kalaburagi Railway Station",
    district: "Kalaburagi",
    police_station: "Railway PS",
    status: "Arrested",
    latitude: 17.3297,
    longitude: 76.8200,
  },
  {
    crime_id: "CRM007",
    crime_type: "Theft",
    date_time: "2024-12-14T23:45:00",
    location: "Indiranagar, Bengaluru",
    district: "Bengaluru Urban",
    police_station: "Indiranagar PS",
    status: "Under Investigation",
    latitude: 12.9784,
    longitude: 77.6408,
  },
  {
    crime_id: "CRM008",
    crime_type: "Murder",
    date_time: "2024-12-14T21:30:00",
    location: "Ballari Old Town",
    district: "Ballari",
    police_station: "Ballari Town PS",
    status: "Under Investigation",
    latitude: 15.1394,
    longitude: 76.9214,
  },
  {
    crime_id: "CRM009",
    crime_type: "Kidnapping",
    date_time: "2024-12-14T18:20:00",
    location: "Ramanagara Highway",
    district: "Ramanagara",
    police_station: "Ramanagara PS",
    status: "Active Search",
    latitude: 12.7167,
    longitude: 77.2814,
  },
  {
    crime_id: "CRM010",
    crime_type: "Cybercrime",
    date_time: "2024-12-14T15:00:00",
    location: "Electronic City, Bengaluru",
    district: "Bengaluru Urban",
    police_station: "Electronic City PS",
    status: "Under Investigation",
    latitude: 12.8397,
    longitude: 77.6720,
  },
];

export const mockMapCrimes = [
  ...mockRecentCrimes,
  { crime_id: "CRM011", crime_type: "Theft", date_time: "2024-12-13T10:00:00", location: "Koramangala, Bengaluru", district: "Bengaluru Urban", police_station: "Koramangala PS", status: "Solved", latitude: 12.9352, longitude: 77.6245, victim_id: "VIC011", suspect_id: "SUS011" },
  { crime_id: "CRM012", crime_type: "Assault", date_time: "2024-12-13T15:30:00", location: "Manipal, Udupi", district: "Udupi", police_station: "Manipal PS", status: "FIR Filed", latitude: 13.3525, longitude: 74.7847, victim_id: "VIC012", suspect_id: null },
  { crime_id: "CRM013", crime_type: "Robbery", date_time: "2024-12-12T20:00:00", location: "Mangaluru Port", district: "Dakshina Kannada", police_station: "Port PS", status: "Under Investigation", latitude: 12.8654, longitude: 74.8426, victim_id: "VIC013", suspect_id: "SUS013" },
  { crime_id: "CRM014", crime_type: "Drug Offense", date_time: "2024-12-12T02:00:00", location: "Vijayapura Bus Stand", district: "Vijayapura", police_station: "Vijayapura Central PS", status: "Arrested", latitude: 16.8302, longitude: 75.7100, victim_id: null, suspect_id: "SUS014" },
  { crime_id: "CRM015", crime_type: "Fraud", date_time: "2024-12-11T11:00:00", location: "Tumakuru Town", district: "Tumakuru", police_station: "Tumakuru PS", status: "Under Investigation", latitude: 13.3392, longitude: 77.1008, victim_id: "VIC015", suspect_id: null },
  { crime_id: "CRM016", crime_type: "Vehicle Theft", date_time: "2024-12-11T08:00:00", location: "Shivamogga Market", district: "Shivamogga", police_station: "Shivamogga PS", status: "FIR Filed", latitude: 13.9299, longitude: 75.5681, victim_id: "VIC016", suspect_id: null },
  { crime_id: "CRM017", crime_type: "Burglary", date_time: "2024-12-10T03:00:00", location: "Hassan Town", district: "Hassan", police_station: "Hassan PS", status: "Solved", latitude: 13.0072, longitude: 76.0962, victim_id: "VIC017", suspect_id: "SUS017" },
  { crime_id: "CRM018", crime_type: "Murder", date_time: "2024-12-10T22:00:00", location: "Raichur Town", district: "Raichur", police_station: "Raichur PS", status: "Under Investigation", latitude: 16.2076, longitude: 77.3561, victim_id: "VIC018", suspect_id: null },
  { crime_id: "CRM019", crime_type: "Theft", date_time: "2024-12-09T14:00:00", location: "Chikkamagaluru Market", district: "Chikkamagaluru", police_station: "Chikkamagaluru PS", status: "FIR Filed", latitude: 13.3172, longitude: 75.7720, victim_id: "VIC019", suspect_id: null },
  { crime_id: "CRM020", crime_type: "Assault", date_time: "2024-12-09T19:00:00", location: "Davanagere Central", district: "Davanagere", police_station: "Davanagere PS", status: "Arrested", latitude: 14.4644, longitude: 75.9218, victim_id: "VIC020", suspect_id: "SUS020" },
];

export const mockHotspotClusters = [
  { hotspot_id: "HS001", location: "Whitefield, Bengaluru", district: "Bengaluru Urban", latitude: 12.9698, longitude: 77.7500, intensity: 95, risk_level: "High", crime_count: 287, most_common_crime: "Vehicle Theft", trend: "Increasing" },
  { hotspot_id: "HS002", location: "Shivajinagar, Bengaluru", district: "Bengaluru Urban", latitude: 12.9822, longitude: 77.6001, intensity: 88, risk_level: "High", crime_count: 243, most_common_crime: "Robbery", trend: "Stable" },
  { hotspot_id: "HS003", location: "Kalaburagi Central", district: "Kalaburagi", latitude: 17.3297, longitude: 76.8200, intensity: 76, risk_level: "High", crime_count: 198, most_common_crime: "Drug Offense", trend: "Increasing" },
  { hotspot_id: "HS004", location: "Ballari Mining Belt", district: "Ballari", latitude: 15.1394, longitude: 76.9214, intensity: 71, risk_level: "High", crime_count: 176, most_common_crime: "Assault", trend: "Stable" },
  { hotspot_id: "HS005", location: "Mysuru Palace Area", district: "Mysuru", latitude: 12.3050, longitude: 76.6551, intensity: 65, risk_level: "Medium", crime_count: 154, most_common_crime: "Theft", trend: "Decreasing" },
  { hotspot_id: "HS006", location: "Mangaluru Port", district: "Dakshina Kannada", latitude: 12.8654, longitude: 74.8426, intensity: 62, risk_level: "Medium", crime_count: 143, most_common_crime: "Robbery", trend: "Stable" },
  { hotspot_id: "HS007", location: "Vijayapura Town", district: "Vijayapura", latitude: 16.8302, longitude: 75.7100, intensity: 58, risk_level: "Medium", crime_count: 132, most_common_crime: "Drug Offense", trend: "Increasing" },
  { hotspot_id: "HS008", location: "Belagavi Market", district: "Belagavi", latitude: 15.8497, longitude: 74.4977, intensity: 54, risk_level: "Medium", crime_count: 121, most_common_crime: "Fraud", trend: "Stable" },
  { hotspot_id: "HS009", location: "Raichur Town Center", district: "Raichur", latitude: 16.2076, longitude: 77.3561, intensity: 48, risk_level: "Medium", crime_count: 109, most_common_crime: "Theft", trend: "Decreasing" },
  { hotspot_id: "HS010", location: "Dharwad Commercial", district: "Dharwad", latitude: 15.4589, longitude: 75.0078, intensity: 42, risk_level: "Low", crime_count: 97, most_common_crime: "Burglary", trend: "Stable" },
];

export const mockTimePatternData = Array.from({ length: 24 }, (_, i) => ({
  hour: i,
  label: `${i}:00`,
  crimes: Math.floor(Math.random() * 80 + 10) + (i >= 20 || i <= 4 ? 40 : 0),
}));

export const mockDayPatternData = [
  { day: "Mon", crimes: 312 },
  { day: "Tue", crimes: 287 },
  { day: "Wed", crimes: 298 },
  { day: "Thu", crimes: 321 },
  { day: "Fri", crimes: 378 },
  { day: "Sat", crimes: 456 },
  { day: "Sun", crimes: 432 },
];

export const mockMonthPatternData = [
  { month: "Jan", crimes: 2100 },
  { month: "Feb", crimes: 1850 },
  { month: "Mar", crimes: 2300 },
  { month: "Apr", crimes: 2450 },
  { month: "May", crimes: 2650 },
  { month: "Jun", crimes: 2800 },
  { month: "Jul", crimes: 2900 },
  { month: "Aug", crimes: 2600 },
  { month: "Sep", crimes: 2400 },
  { month: "Oct", crimes: 2750 },
  { month: "Nov", crimes: 2850 },
  { month: "Dec", crimes: 2847 },
];

export const mockDeploymentSuggestions = {
  ai_generated: true,
  suggestions: [
    { area: "Whitefield, Bengaluru", patrol_timing: "8PM - 4AM", officers_needed: 12, priority: "Critical", reason: "High vehicle theft rate during late hours" },
    { area: "Shivajinagar, Bengaluru", patrol_timing: "6PM - 2AM", officers_needed: 8, priority: "High", reason: "Robbery spike on weekends" },
    { area: "Kalaburagi Central", patrol_timing: "10PM - 6AM", officers_needed: 6, priority: "High", reason: "Drug trafficking routes active at night" },
    { area: "Ballari Mining Belt", patrol_timing: "All day", officers_needed: 10, priority: "High", reason: "Organized crime activity around mining areas" },
    { area: "Mysuru Palace Area", patrol_timing: "9AM - 9PM", officers_needed: 5, priority: "Medium", reason: "Tourist area theft prevention" },
  ],
  ai_summary: "Based on spatiotemporal analysis, the highest priority deployment should focus on Whitefield and Shivajinagar in Bengaluru Urban, particularly during evening and night hours. Kalaburagi Central requires increased night patrolling to disrupt drug trafficking routes identified by network analysis.",
};

export const mockNetworkNodes = [
  { node_id: "N001", node_type: "criminal", label: "Rajan Mehta", risk_score: 92, crime_count: 14, profile_data: { age: 34, district: "Bengaluru Urban", status: "Active" } },
  { node_id: "N002", node_type: "criminal", label: "Suresh Naik", risk_score: 78, crime_count: 9, profile_data: { age: 28, district: "Kalaburagi", status: "Absconding" } },
  { node_id: "N003", node_type: "criminal", label: "Mohammad Ilyas", risk_score: 85, crime_count: 11, profile_data: { age: 42, district: "Belagavi", status: "Active" } },
  { node_id: "N004", node_type: "criminal", label: "Ramesh Gowda", risk_score: 65, crime_count: 6, profile_data: { age: 31, district: "Mysuru", status: "Imprisoned" } },
  { node_id: "N005", node_type: "victim", label: "Priya Sharma", risk_score: 0, crime_count: 0, profile_data: { age: 26, district: "Bengaluru Urban" } },
  { node_id: "N006", node_type: "victim", label: "Karim Khan", risk_score: 0, crime_count: 0, profile_data: { age: 45, district: "Belagavi" } },
  { node_id: "N007", node_type: "location", label: "Whitefield Hub", risk_score: 88, crime_count: 287, profile_data: { address: "Whitefield, Bengaluru", type: "Crime Hub" } },
  { node_id: "N008", node_type: "location", label: "Kalaburagi Warehouse", risk_score: 74, crime_count: 45, profile_data: { address: "Industrial Area, Kalaburagi", type: "Storage Facility" } },
  { node_id: "N009", node_type: "organization", label: "Shell Company A", risk_score: 81, crime_count: 23, profile_data: { type: "Money Laundering", registered: "Bengaluru" } },
  { node_id: "N010", node_type: "criminal", label: "Venkat Reddy", risk_score: 71, crime_count: 7, profile_data: { age: 38, district: "Ballari", status: "Active" } },
  { node_id: "N011", node_type: "organization", label: "Drug Syndicate B", risk_score: 93, crime_count: 67, profile_data: { type: "Drug Trafficking", registered: "Unknown" } },
  { node_id: "N012", node_type: "criminal", label: "Ajay Shetty", risk_score: 69, crime_count: 5, profile_data: { age: 25, district: "Dakshina Kannada", status: "Active" } },
];

export const mockNetworkEdges = [
  { source: "N001", target: "N002", relationship_type: "Associate", strength_score: 85 },
  { source: "N001", target: "N003", relationship_type: "Co-conspirator", strength_score: 92 },
  { source: "N001", target: "N007", relationship_type: "Frequent Location", strength_score: 78 },
  { source: "N001", target: "N009", relationship_type: "Financial Link", strength_score: 65 },
  { source: "N002", target: "N008", relationship_type: "Frequent Location", strength_score: 70 },
  { source: "N002", target: "N011", relationship_type: "Member", strength_score: 88 },
  { source: "N003", target: "N006", relationship_type: "Victim", strength_score: 45 },
  { source: "N003", target: "N009", relationship_type: "Financial Link", strength_score: 73 },
  { source: "N004", target: "N005", relationship_type: "Victim", strength_score: 55 },
  { source: "N004", target: "N007", relationship_type: "Frequent Location", strength_score: 62 },
  { source: "N010", target: "N001", relationship_type: "Associate", strength_score: 58 },
  { source: "N010", target: "N011", relationship_type: "Supplier", strength_score: 82 },
  { source: "N011", target: "N008", relationship_type: "Storage", strength_score: 76 },
  { source: "N012", target: "N003", relationship_type: "Associate", strength_score: 67 },
  { source: "N012", target: "N011", relationship_type: "Member", strength_score: 79 },
];

export const mockAiNetworkSummary = {
  summary: "Analysis reveals a sophisticated multi-district criminal network centered around Rajan Mehta (N001) and Mohammad Ilyas (N003) with strong financial links through Shell Company A. The network has tentacles in drug trafficking (Drug Syndicate B), organized vehicle theft in Whitefield, and cross-border smuggling through Belagavi. Immediate action recommended to disrupt financial flows.",
  suspicious_associations: [
    { entities: ["N001", "N003", "N009"], reason: "Suspected money laundering operation", severity: "Critical" },
    { entities: ["N002", "N010", "N011"], reason: "Drug supply chain network", severity: "High" },
    { entities: ["N012", "N003"], reason: "New association suggesting expansion of operations", severity: "Medium" },
  ],
  investigation_priorities: ["Freeze financial accounts linked to N009", "Locate and apprehend Suresh Naik (N002)", "Raid Kalaburagi warehouse (N008)"],
};

export const mockOffenders = [
  {
    offender_id: "OFF001",
    offender_name: "Rajan Mehta",
    offender_age: 34,
    date_of_birth: "1990-03-15",
    physical_description: "Height: 5'9\", Weight: 75kg, Dark complexion, Scar on left cheek",
    offender_status: "Active",
    risk_level: "High",
    risk_score: 92,
    district: "Bengaluru Urban",
    crime_history: [
      { crime_id: "CRM_H001", crime_type: "Robbery", date: "2024-11-12", location: "MG Road", outcome: "Absconded" },
      { crime_id: "CRM_H002", crime_type: "Vehicle Theft", date: "2024-09-05", location: "Whitefield", outcome: "Case Pending" },
      { crime_id: "CRM_H003", crime_type: "Assault", date: "2024-06-20", location: "Indiranagar", outcome: "Bail Granted" },
      { crime_id: "CRM_H004", crime_type: "Robbery", date: "2023-12-08", location: "HSR Layout", outcome: "Acquitted" },
      { crime_id: "CRM_H005", crime_type: "Burglary", date: "2023-08-14", location: "Koramangala", outcome: "Convicted" },
    ],
    modus_operandi: {
      preferred_crime_types: ["Robbery", "Vehicle Theft", "Burglary"],
      preferred_locations: ["Commercial areas", "Parking lots", "Residential neighborhoods"],
      preferred_time: "Late evening (8PM-12AM)",
      weapons_methods: ["Physical intimidation", "Lock picking tools", "Stolen vehicles"],
      typical_target: "Working professionals, vehicle owners",
      escape_patterns: "Uses auto-rickshaws, changes routes frequently",
    },
    associates_list: [
      { associate_id: "OFF002", name: "Suresh Naik", relationship: "Gang Member" },
      { associate_id: "OFF003", name: "Mohammad Ilyas", relationship: "Co-conspirator" },
    ],
    linked_locations: [
      { name: "Whitefield Hub", latitude: 12.9698, longitude: 77.7500 },
      { name: "Koramangala Safe House", latitude: 12.9352, longitude: 77.6245 },
    ],
    ai_assessment: "High recidivism risk. Pattern analysis indicates likelihood of escalation to violent crimes. Recommended for enhanced surveillance. Network connections suggest involvement in organized crime syndicate.",
    reoffend_probability: 89,
  },
  {
    offender_id: "OFF002",
    offender_name: "Suresh Naik",
    offender_age: 28,
    date_of_birth: "1996-07-22",
    physical_description: "Height: 5'7\", Weight: 68kg, Medium complexion, Tattoo on right arm",
    offender_status: "Absconding",
    risk_level: "High",
    risk_score: 78,
    district: "Kalaburagi",
    crime_history: [
      { crime_id: "CRM_H006", crime_type: "Drug Offense", date: "2024-10-15", location: "Kalaburagi Central", outcome: "Absconded" },
      { crime_id: "CRM_H007", crime_type: "Assault", date: "2024-07-03", location: "Gulbarga Naka", outcome: "Bail Granted" },
      { crime_id: "CRM_H008", crime_type: "Robbery", date: "2024-02-18", location: "Railway Station", outcome: "Convicted" },
    ],
    modus_operandi: {
      preferred_crime_types: ["Drug Offense", "Robbery", "Assault"],
      preferred_locations: ["Railway stations", "Bus stands", "Night markets"],
      preferred_time: "Night (10PM-4AM)",
      weapons_methods: ["Controlled substances", "Bladed weapons"],
      typical_target: "Travelers, shopkeepers",
      escape_patterns: "Uses interstate buses, known to cross into Maharashtra",
    },
    associates_list: [
      { associate_id: "OFF001", name: "Rajan Mehta", relationship: "Gang Leader" },
    ],
    linked_locations: [
      { name: "Kalaburagi Warehouse", latitude: 17.3297, longitude: 76.8200 },
    ],
    ai_assessment: "Currently absconding. High risk to public safety. Drug trafficking network connections. Likely in Maharashtra border regions. Coordinate with Maharashtra Police immediately.",
    reoffend_probability: 94,
  },
  {
    offender_id: "OFF003",
    offender_name: "Mohammad Ilyas",
    offender_age: 42,
    date_of_birth: "1982-11-08",
    physical_description: "Height: 6'0\", Weight: 85kg, Fair complexion, Beard",
    offender_status: "Active",
    risk_level: "High",
    risk_score: 85,
    district: "Belagavi",
    crime_history: [
      { crime_id: "CRM_H009", crime_type: "Extortion", date: "2024-12-01", location: "Belagavi Market", outcome: "Case Pending" },
      { crime_id: "CRM_H010", crime_type: "Human Trafficking", date: "2024-08-20", location: "Belagavi Border", outcome: "Under Investigation" },
      { crime_id: "CRM_H011", crime_type: "Fraud", date: "2024-04-10", location: "Belagavi City", outcome: "Acquitted" },
    ],
    modus_operandi: {
      preferred_crime_types: ["Extortion", "Human Trafficking", "Fraud"],
      preferred_locations: ["Border areas", "Commercial establishments", "Markets"],
      preferred_time: "Business hours (9AM-5PM)",
      weapons_methods: ["Intimidation through associates", "Forged documents"],
      typical_target: "Business owners, migrants",
      escape_patterns: "Has connections in Goa and Maharashtra for refuge",
    },
    associates_list: [
      { associate_id: "OFF001", name: "Rajan Mehta", relationship: "Business Partner" },
      { associate_id: "OFF004", name: "Ajay Shetty", relationship: "Subordinate" },
    ],
    linked_locations: [
      { name: "Belagavi Border Checkpoint", latitude: 15.8497, longitude: 74.4977 },
    ],
    ai_assessment: "Sophisticated criminal operating cross-border networks. Financial crime expertise. Links to organized crime in multiple states. International cooperation may be required for full investigation.",
    reoffend_probability: 76,
  },
  {
    offender_id: "OFF004",
    offender_name: "Ramesh Gowda",
    offender_age: 31,
    date_of_birth: "1993-04-25",
    physical_description: "Height: 5'8\", Weight: 72kg, Dark complexion",
    offender_status: "Imprisoned",
    risk_level: "Medium",
    risk_score: 65,
    district: "Mysuru",
    crime_history: [
      { crime_id: "CRM_H012", crime_type: "Theft", date: "2024-01-15", location: "Mysuru Palace", outcome: "Convicted" },
      { crime_id: "CRM_H013", crime_type: "Burglary", date: "2023-09-08", location: "Mysuru Residential", outcome: "Convicted" },
    ],
    modus_operandi: {
      preferred_crime_types: ["Theft", "Burglary"],
      preferred_locations: ["Tourist areas", "Residential colonies"],
      preferred_time: "Early morning (4AM-8AM)",
      weapons_methods: ["Lock bypass tools", "Operates alone"],
      typical_target: "Tourists, empty homes",
      escape_patterns: "Uses public transport",
    },
    associates_list: [],
    linked_locations: [
      { name: "Mysuru Palace Area", latitude: 12.3050, longitude: 76.6551 },
    ],
    ai_assessment: "Currently imprisoned. Release date: March 2025. Medium reoffend risk. Recommend rehabilitation programs and monitoring post-release.",
    reoffend_probability: 52,
  },
];

export const mockDistrictRiskScores = [
  { district: "Bengaluru Urban", risk_score: 92, risk_level: "High", latitude: 12.97, longitude: 77.59 },
  { district: "Kalaburagi", risk_score: 78, risk_level: "High", latitude: 17.33, longitude: 76.82 },
  { district: "Ballari", risk_score: 74, risk_level: "High", latitude: 15.14, longitude: 76.92 },
  { district: "Belagavi", risk_score: 71, risk_level: "High", latitude: 15.85, longitude: 74.50 },
  { district: "Raichur", risk_score: 68, risk_level: "Medium", latitude: 16.20, longitude: 77.36 },
  { district: "Mysuru", risk_score: 65, risk_level: "Medium", latitude: 12.29, longitude: 76.64 },
  { district: "Vijayapura", risk_score: 62, risk_level: "Medium", latitude: 16.83, longitude: 75.72 },
  { district: "Dakshina Kannada", risk_score: 58, risk_level: "Medium", latitude: 12.86, longitude: 75.04 },
  { district: "Davanagere", risk_score: 54, risk_level: "Medium", latitude: 14.46, longitude: 75.92 },
  { district: "Dharwad", risk_score: 48, risk_level: "Medium", latitude: 15.46, longitude: 75.02 },
  { district: "Shivamogga", risk_score: 44, risk_level: "Low", latitude: 13.93, longitude: 75.56 },
  { district: "Hassan", risk_score: 38, risk_level: "Low", latitude: 13.00, longitude: 76.10 },
  { district: "Chikkamagaluru", risk_score: 35, risk_level: "Low", latitude: 13.32, longitude: 75.77 },
  { district: "Tumakuru", risk_score: 42, risk_level: "Low", latitude: 13.34, longitude: 77.10 },
  { district: "Mandya", risk_score: 36, risk_level: "Low", latitude: 12.52, longitude: 76.90 },
];

export const mockHighRiskPredictions = [
  { prediction_id: "PRD001", location: "Whitefield, Bengaluru", district: "Bengaluru Urban", predicted_crime_type: "Vehicle Theft", risk_percentage: 87, confidence_level: 92, prediction_date: "2024-12-22", recommended_action: "Deploy 10 additional patrol vehicles, install surveillance cameras at parking lots" },
  { prediction_id: "PRD002", location: "Kalaburagi Central Market", district: "Kalaburagi", predicted_crime_type: "Drug Offense", risk_percentage: 83, confidence_level: 88, prediction_date: "2024-12-20", recommended_action: "Conduct surprise checks, establish informant network in market area" },
  { prediction_id: "PRD003", location: "Ballari Mining Area", district: "Ballari", predicted_crime_type: "Assault", risk_percentage: 78, confidence_level: 85, prediction_date: "2024-12-21", recommended_action: "Increase police presence near mining sites, coordinate with mine management" },
  { prediction_id: "PRD004", location: "Belagavi Border", district: "Belagavi", predicted_crime_type: "Smuggling", risk_percentage: 74, confidence_level: 79, prediction_date: "2024-12-23", recommended_action: "Enhance border checkpost monitoring, coordinate with customs" },
  { prediction_id: "PRD005", location: "MG Road, Bengaluru", district: "Bengaluru Urban", predicted_crime_type: "Robbery", risk_percentage: 71, confidence_level: 82, prediction_date: "2024-12-24", recommended_action: "Increase foot patrol, install panic buttons in shops" },
];

export const mockCrimeForecast = Array.from({ length: 30 }, (_, i) => {
  const base = 2847 + Math.sin(i * 0.3) * 150;
  return {
    day: i + 1,
    date: new Date(2024, 11, 16 + i).toISOString().split("T")[0],
    predicted: Math.floor(base + Math.random() * 100 - 50),
    upper_bound: Math.floor(base + 200),
    lower_bound: Math.floor(base - 200),
    historical: i < 10 ? Math.floor(base + Math.random() * 80 - 40) : null,
  };
});

export const mockEmergingTypologies = [
  { typology: "Digital Payment Fraud", growth_rate: "+156%", first_detected: "2024-10-01", description: "New methods targeting UPI and digital wallet users using fake QR codes", ai_insight: "Coordinated gang using AI-generated fake merchant pages" },
  { typology: "Vehicle-Based Snatch Theft", growth_rate: "+89%", first_detected: "2024-11-15", description: "Motorcycle-mounted thieves targeting pedestrians with mobile phones", ai_insight: "Pattern matches organized gang with escape routes pre-planned" },
  { typology: "Rural Land Fraud", growth_rate: "+67%", first_detected: "2024-09-01", description: "Forged documents being used to fraudulently transfer land titles in rural districts", ai_insight: "Connected to organized land mafia with links to document forgery networks" },
];

export const mockSocioeconomicData = [
  { district: "Bengaluru Urban", unemployment_rate: 4.2, population_density: 4378, urbanization: 100, poverty_index: 12.3 },
  { district: "Kalaburagi", unemployment_rate: 12.8, population_density: 245, urbanization: 28, poverty_index: 34.7 },
  { district: "Ballari", unemployment_rate: 9.4, population_density: 312, urbanization: 41, poverty_index: 28.9 },
  { district: "Belagavi", unemployment_rate: 7.6, population_density: 287, urbanization: 35, poverty_index: 22.4 },
  { district: "Mysuru", unemployment_rate: 5.8, population_density: 456, urbanization: 62, poverty_index: 18.7 },
];

export const mockAnomalies = [
  {
    anomaly_id: "ANO001",
    detection_datetime: "2024-12-15T09:30:00",
    anomaly_type: "Crime Spike",
    severity_level: "Critical",
    location: "Whitefield, Bengaluru",
    description: "Vehicle theft rate increased by 340% in a 48-hour window",
    ai_explanation: "Gemini AI Analysis: The sudden spike in vehicle thefts in Whitefield (287% above seasonal baseline) appears to be coordinated. Social media analysis shows no local festivals or events that could explain the crowd. Network analysis links 4 of the 12 vehicles stolen to the same parking facility. High probability (94%) of organized theft ring operation.",
    related_cases: ["CRM001", "CRM007", "CRM011"],
    evidence_points: ["12 vehicles stolen in 48 hours", "Same parking facility targeted multiple times", "Victims report similar suspect descriptions", "CCTV shows same vehicle circling area"],
    recommended_action: "Deploy plainclothes officers at targeted parking facilities. Issue BOLO for suspects. Check pawn shops and scrap dealers in 50km radius.",
    status: "Under Review",
    assigned_officer: "Inspector Ramesh Kumar",
  },
  {
    anomaly_id: "ANO002",
    detection_datetime: "2024-12-14T18:45:00",
    anomaly_type: "Cross-District Pattern",
    severity_level: "Critical",
    location: "Belagavi Border Areas",
    description: "Unusual pattern of incidents at border checkpoints suggesting smuggling operation",
    ai_explanation: "Gemini AI Analysis: Analysis of 23 separate incidents over 7 days reveals a systematic pattern: low-value decoy items being seized at main checkpoints while high-value contraband passes through secondary routes. The timing intervals between incidents show mathematical precision suggesting coordinated communication.",
    related_cases: ["CRM003", "CRM013"],
    evidence_points: ["23 incidents in 7 days", "Systematic decoy pattern", "Precise timing intervals", "Cross-state vehicle registrations"],
    recommended_action: "Secret checkpoints at secondary routes. Intelligence sharing with Maharashtra and Goa police. Financial investigation of known transporters.",
    status: "New",
    assigned_officer: null,
  },
  {
    anomaly_id: "ANO003",
    detection_datetime: "2024-12-14T14:20:00",
    anomaly_type: "Network Expansion",
    severity_level: "High",
    location: "Multiple Districts",
    description: "Criminal network analysis shows rapid expansion of known gang across 5 new districts",
    ai_explanation: "Gemini AI Analysis: Network topology analysis shows Drug Syndicate B (known entity) has added 8 new nodes in the past 30 days, spanning 5 previously unaffected districts. Expansion pattern matches historical MO of criminal organizations that have successfully evaded law enforcement in home district. Recommend preemptive action before network consolidates.",
    related_cases: ["CRM006", "CRM014"],
    evidence_points: ["8 new network nodes in 30 days", "5 new districts affected", "Financial transaction pattern matches", "Phone tower data links new members"],
    recommended_action: "Multi-district coordinated raids within 72 hours. SWIFT financial freeze on flagged accounts. Media blackout during operation.",
    status: "Under Review",
    assigned_officer: "SP Vijay Sharma",
  },
  {
    anomaly_id: "ANO004",
    detection_datetime: "2024-12-14T10:00:00",
    anomaly_type: "Victim Pattern",
    severity_level: "High",
    location: "Mysuru Tourist Areas",
    description: "Unusual concentration of fraud cases targeting tourists in Mysuru",
    ai_explanation: "Gemini AI Analysis: 23 fraud cases this month all targeting tourists, compared to 3 in the same period last year. All victims report being approached by individuals near major tourist sites. Language pattern analysis of FIR descriptions shows high similarity suggesting same group using scripted approaches. Tourist police deployment recommended immediately.",
    related_cases: ["CRM004", "CRM015"],
    evidence_points: ["23 tourist-targeted fraud cases", "Scripted approach pattern", "Near major tourist sites", "Similar suspect descriptions"],
    recommended_action: "Deploy tourist police at all major sites. Issue tourist advisory. Coordinate with hotels and tour operators.",
    status: "Resolved",
    assigned_officer: "Inspector Sheela Devi",
  },
  {
    anomaly_id: "ANO005",
    detection_datetime: "2024-12-13T22:00:00",
    anomaly_type: "Temporal Anomaly",
    severity_level: "Medium",
    location: "Raichur District",
    description: "Drug offenses spiking exclusively between 2AM-4AM in specific week pattern",
    ai_explanation: "Gemini AI Analysis: Temporal analysis reveals drug transactions concentrated in a 2-hour window (2AM-4AM) on Tuesdays and Thursdays only. This precision suggests a fixed supply schedule. Geospatial analysis points to highway NH-50 as likely transit route. Cross-referencing commercial vehicle logs could identify suppliers.",
    related_cases: ["CRM018"],
    evidence_points: ["2AM-4AM exclusive pattern", "Tuesday-Thursday only", "NH-50 proximity", "Consistent geographic clustering"],
    recommended_action: "Surveillance on NH-50 during target time windows. Check commercial vehicle manifests. Plain-clothes operations.",
    status: "New",
    assigned_officer: null,
  },
];

export const mockUsers = [
  { user_id: "USR001", user_name: "Suresh Kumar", email: "suresh.kumar@ksp.gov.in", role: "SCRB Officer", district: "State Level", status: "Active", last_login: "2024-12-15T14:30:00" },
  { user_id: "USR002", user_name: "Anita Rao", email: "anita.rao@ksp.gov.in", role: "District Officer", district: "Bengaluru Urban", status: "Active", last_login: "2024-12-15T13:00:00" },
  { user_id: "USR003", user_name: "Ravi Shankar", email: "ravi.shankar@ksp.gov.in", role: "Investigator", district: "Mysuru", status: "Active", last_login: "2024-12-14T18:00:00" },
  { user_id: "USR004", user_name: "Priya Devi", email: "priya.devi@ksp.gov.in", role: "District Officer", district: "Kalaburagi", status: "Active", last_login: "2024-12-15T09:00:00" },
  { user_id: "USR005", user_name: "Manjunath", email: "manjunath@ksp.gov.in", role: "Investigator", district: "Belagavi", status: "Inactive", last_login: "2024-12-10T10:00:00" },
];

export const mockDataSources = [
  { source_id: "DS001", source_name: "CCTNS (Crime & Criminal Tracking Network)", status: "Connected", last_sync: "2024-12-15T14:00:00", record_count: 1248965 },
  { source_id: "DS002", source_name: "Vehicle Registration Database", status: "Connected", last_sync: "2024-12-15T12:00:00", record_count: 8567432 },
  { source_id: "DS003", source_name: "Census Socioeconomic Data", status: "Connected", last_sync: "2024-12-01T00:00:00", record_count: 61130704 },
  { source_id: "DS004", source_name: "CCTV Footage Analysis System", status: "Partial", last_sync: "2024-12-15T10:00:00", record_count: 45230 },
  { source_id: "DS005", source_name: "Financial Intelligence Unit", status: "Pending", last_sync: "2024-12-12T00:00:00", record_count: 234567 },
];

export const mockAlertThresholds = {
  crime_spike_threshold: 150,
  hotspot_minimum_crimes: 10,
  risk_score_alert: 75,
  network_connection_alert: true,
  prediction_confidence_alert: 80,
  anomaly_severity_alert: "Medium",
  email_notifications: true,
  sms_notifications: true,
  notification_email: "alerts@ksp.gov.in",
};

export const mockSavedReports = [
  { report_id: "RPT001", report_type: "District Summary", district: "Bengaluru Urban", date_range: "Nov 2024", generated_at: "2024-12-01T10:00:00", generated_by: "Suresh Kumar" },
  { report_id: "RPT002", report_type: "Crime Trend", district: "All Karnataka", date_range: "Q3 2024", generated_at: "2024-10-15T14:00:00", generated_by: "Anita Rao" },
  { report_id: "RPT003", report_type: "Hotspot Analysis", district: "Kalaburagi", date_range: "Oct 2024", generated_at: "2024-11-01T09:00:00", generated_by: "Priya Devi" },
  { report_id: "RPT004", report_type: "Offender Activity", district: "All Karnataka", date_range: "2024 Annual", generated_at: "2024-11-30T16:00:00", generated_by: "Suresh Kumar" },
];

export const mockNetworkData = {
  nodes: mockNetworkNodes,
  edges: mockNetworkEdges,
};
