export const KARNATAKA_DISTRICTS = [
  "All Districts",
  "Bagalkot",
  "Ballari",
  "Belagavi",
  "Bengaluru Rural",
  "Bengaluru Urban",
  "Bidar",
  "Chamarajanagar",
  "Chikkaballapur",
  "Chikkamagaluru",
  "Chitradurga",
  "Dakshina Kannada",
  "Davangere",
  "Dharwad",
  "Gadag",
  "Hassan",
  "Haveri",
  "Kalaburagi",
  "Kodagu",
  "Kolar",
  "Koppal",
  "Mandya",
  "Mysuru",
  "Raichur",
  "Ramanagara",
  "Shivamogga",
  "Tumakuru",
  "Udupi",
  "Uttara Kannada",
  "Vijayanagara",
  "Vijayapura",
  "Yadgir",
];

export const KARNATAKA_DISTRICTS_WITH_CODES = [
  { district_id: "KA-01", district_name: "Bangalore Urban" },
  { district_id: "KA-02", district_name: "Bangalore Rural" },
  { district_id: "KA-03", district_name: "Mysuru" },
  { district_id: "KA-04", district_name: "Tumakuru" },
  { district_id: "KA-05", district_name: "Kolar" },
  { district_id: "KA-06", district_name: "Chikkaballapur" },
  { district_id: "KA-07", district_name: "Ramanagara" },
  { district_id: "KA-08", district_name: "Mandya" },
  { district_id: "KA-09", district_name: "Chamarajanagar" },
  { district_id: "KA-10", district_name: "Hassan" },
  { district_id: "KA-11", district_name: "Chikkamagaluru" },
  { district_id: "KA-12", district_name: "Kodagu" },
  { district_id: "KA-13", district_name: "Dakshina Kannada" },
  { district_id: "KA-14", district_name: "Udupi" },
  { district_id: "KA-15", district_name: "Uttara Kannada" },
  { district_id: "KA-16", district_name: "Shivamogga" },
  { district_id: "KA-17", district_name: "Davanagere" },
  { district_id: "KA-18", district_name: "Chitradurga" },
  { district_id: "KA-19", district_name: "Ballari" },
  { district_id: "KA-20", district_name: "Koppal" },
  { district_id: "KA-21", district_name: "Raichur" },
  { district_id: "KA-22", district_name: "Kalaburagi" },
  { district_id: "KA-23", district_name: "Yadgir" },
  { district_id: "KA-24", district_name: "Bidar" },
  { district_id: "KA-25", district_name: "Vijayapura" },
  { district_id: "KA-26", district_name: "Bagalkot" },
  { district_id: "KA-27", district_name: "Belagavi" },
  { district_id: "KA-28", district_name: "Dharwad" },
  { district_id: "KA-29", district_name: "Gadag" },
  { district_id: "KA-30", district_name: "Haveri" }
];


export const DISTRICT_COORDINATES: Record<string, [number, number]> = {
  Bagalkot: [16.18, 75.69],
  Ballari: [15.14, 76.92],
  Belagavi: [15.85, 74.5],
  "Bengaluru Rural": [13.21, 77.4],
  "Bengaluru Urban": [12.97, 77.59],
  Bidar: [17.91, 77.52],
  Chamarajanagar: [11.92, 76.94],
  Chikkaballapur: [13.43, 77.73],
  Chikkamagaluru: [13.32, 75.77],
  Chitradurga: [14.23, 76.4],
  "Dakshina Kannada": [12.86, 75.04],
  Davanagere: [14.46, 75.92],
  Dharwad: [15.46, 75.02],
  Gadag: [15.42, 75.62],
  Hassan: [13.0, 76.1],
  Haveri: [14.79, 75.4],
  Kalaburagi: [17.33, 76.82],
  Kodagu: [12.42, 75.74],
  Kolar: [13.14, 78.13],
  Koppal: [15.35, 76.15],
  Mandya: [12.52, 76.9],
  Mysuru: [12.29, 76.64],
  Raichur: [16.2, 77.36],
  Ramanagara: [12.72, 77.28],
  Shivamogga: [13.93, 75.56],
  Tumakuru: [13.34, 77.1],
  Udupi: [13.34, 74.74],
  "Uttara Kannada": [14.79, 74.7],
  Vijayapura: [16.83, 75.72],
  Yadgir: [16.77, 77.14],
};
