"""baseline_all_models

Revision ID: 588535cb0590
Revises: 
Create Date: 2026-07-08 16:10:03.755048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '588535cb0590'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('alert_id', sa.UUID(), nullable=False),
    sa.Column('alert_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('district_id', sa.String(length=50), nullable=True),
    sa.Column('location_id', sa.UUID(), nullable=True),
    sa.Column('related_entity_id', sa.String(length=200), nullable=True),
    sa.Column('related_entity_type', sa.String(length=100), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('read_by', sa.UUID(), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('target_role', sa.String(length=100), nullable=True),
    sa.Column('target_district', sa.String(length=50), nullable=True),
    sa.Column('generated_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('alert_id')
    )
    op.create_index(op.f('ix_alerts_alert_type'), 'alerts', ['alert_type'], unique=False)
    op.create_index(op.f('ix_alerts_district_id'), 'alerts', ['district_id'], unique=False)
    op.create_index(op.f('ix_alerts_is_read'), 'alerts', ['is_read'], unique=False)
    op.create_index(op.f('ix_alerts_severity'), 'alerts', ['severity'], unique=False)
    op.create_table('anomalies',
    sa.Column('anomaly_id', sa.UUID(), nullable=False),
    sa.Column('anomaly_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('district_id', sa.String(length=50), nullable=True),
    sa.Column('location_id', sa.UUID(), nullable=True),
    sa.Column('crime_id', sa.UUID(), nullable=True),
    sa.Column('offender_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('evidence_points', sa.JSON(), nullable=True),
    sa.Column('ai_explanation', sa.Text(), nullable=True),
    sa.Column('related_case_ids', sa.JSON(), nullable=True),
    sa.Column('similar_historical', sa.JSON(), nullable=True),
    sa.Column('recommended_action', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('assigned_officer_id', sa.UUID(), nullable=True),
    sa.Column('anomaly_score', sa.Float(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('anomaly_id')
    )
    op.create_index(op.f('ix_anomalies_anomaly_type'), 'anomalies', ['anomaly_type'], unique=False)
    op.create_index(op.f('ix_anomalies_district_id'), 'anomalies', ['district_id'], unique=False)
    op.create_index(op.f('ix_anomalies_severity'), 'anomalies', ['severity'], unique=False)
    op.create_index(op.f('ix_anomalies_status'), 'anomalies', ['status'], unique=False)
    op.create_table('audit_logs',
    sa.Column('log_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.String(length=100), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('districts',
    sa.Column('district_id', sa.String(length=50), nullable=False),
    sa.Column('district_name', sa.String(length=200), nullable=False),
    sa.Column('district_code', sa.String(length=20), nullable=False),
    sa.Column('headquarters', sa.String(length=200), nullable=False),
    sa.Column('total_area_sqkm', sa.Float(), nullable=True),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('boundary_geojson', sa.JSON(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('district_id')
    )
    op.create_table('predictions',
    sa.Column('prediction_id', sa.UUID(), nullable=False),
    sa.Column('prediction_type', sa.String(length=100), nullable=False),
    sa.Column('district_id', sa.String(length=50), nullable=True),
    sa.Column('location_id', sa.UUID(), nullable=True),
    sa.Column('predicted_crime_type', sa.String(length=100), nullable=True),
    sa.Column('risk_percentage', sa.Float(), nullable=True),
    sa.Column('confidence_level', sa.Float(), nullable=True),
    sa.Column('prediction_date', sa.Date(), nullable=True),
    sa.Column('prediction_made_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('features_used', sa.JSON(), nullable=True),
    sa.Column('actual_outcome', sa.String(length=200), nullable=True),
    sa.Column('accuracy_score', sa.Float(), nullable=True),
    sa.Column('recommended_action', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('contributing_factors', sa.JSON(), nullable=True),
    sa.Column('forecast_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('prediction_id')
    )
    op.create_index(op.f('ix_predictions_district_id'), 'predictions', ['district_id'], unique=False)
    op.create_index(op.f('ix_predictions_prediction_type'), 'predictions', ['prediction_type'], unique=False)
    op.create_table('reports',
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('report_type', sa.String(length=100), nullable=False),
    sa.Column('report_name', sa.String(length=500), nullable=False),
    sa.Column('generated_by', sa.UUID(), nullable=True),
    sa.Column('date_from', sa.Date(), nullable=True),
    sa.Column('date_to', sa.Date(), nullable=True),
    sa.Column('district_id', sa.String(length=50), nullable=True),
    sa.Column('crime_types_included', sa.JSON(), nullable=True),
    sa.Column('report_data', sa.JSON(), nullable=True),
    sa.Column('ai_narrative', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crime_spike_percent', sa.Integer(), nullable=True),
    sa.Column('anomaly_confidence', sa.Integer(), nullable=True),
    sa.Column('high_risk_score', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('district_id', sa.String(length=50), nullable=True),
    sa.Column('police_station_id', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('hotspots',
    sa.Column('hotspot_id', sa.UUID(), nullable=False),
    sa.Column('hotspot_name', sa.String(length=300), nullable=False),
    sa.Column('district_id', sa.String(length=50), nullable=False),
    sa.Column('center_latitude', sa.Float(), nullable=False),
    sa.Column('center_longitude', sa.Float(), nullable=False),
    sa.Column('radius_meters', sa.Float(), nullable=True),
    sa.Column('boundary_geojson', sa.JSON(), nullable=True),
    sa.Column('crime_count', sa.Integer(), nullable=True),
    sa.Column('dominant_crime_type', sa.String(length=100), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('peak_time_start', sa.String(length=10), nullable=True),
    sa.Column('peak_time_end', sa.String(length=10), nullable=True),
    sa.Column('peak_days', sa.JSON(), nullable=True),
    sa.Column('trend', sa.String(length=20), nullable=True),
    sa.Column('trend_percentage', sa.Float(), nullable=True),
    sa.Column('deployment_suggestion', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['district_id'], ['districts.district_id'], ),
    sa.PrimaryKeyConstraint('hotspot_id')
    )
    op.create_index(op.f('ix_hotspots_district_id'), 'hotspots', ['district_id'], unique=False)
    op.create_table('offenders',
    sa.Column('offender_id', sa.UUID(), nullable=False),
    sa.Column('offender_reference', sa.String(length=100), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('alias_names', sa.JSON(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('nationality', sa.String(length=100), nullable=True),
    sa.Column('religion', sa.String(length=100), nullable=True),
    sa.Column('caste', sa.String(length=100), nullable=True),
    sa.Column('education_level', sa.String(length=100), nullable=True),
    sa.Column('occupation', sa.String(length=200), nullable=True),
    sa.Column('address_current', sa.Text(), nullable=True),
    sa.Column('address_permanent', sa.Text(), nullable=True),
    sa.Column('district_id', sa.String(length=50), nullable=True),
    sa.Column('latitude_home', sa.Float(), nullable=True),
    sa.Column('longitude_home', sa.Float(), nullable=True),
    sa.Column('phone_numbers', sa.JSON(), nullable=True),
    sa.Column('physical_description', sa.Text(), nullable=True),
    sa.Column('identifying_marks', sa.Text(), nullable=True),
    sa.Column('photo_available', sa.Boolean(), nullable=True),
    sa.Column('fingerprint_available', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('prison_name', sa.String(length=300), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('total_crimes', sa.Integer(), nullable=True),
    sa.Column('first_offense_date', sa.Date(), nullable=True),
    sa.Column('last_offense_date', sa.Date(), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('modus_operandi_summary', sa.Text(), nullable=True),
    sa.Column('preferred_crime_types', sa.JSON(), nullable=True),
    sa.Column('preferred_locations', sa.JSON(), nullable=True),
    sa.Column('preferred_time', sa.String(length=50), nullable=True),
    sa.Column('typical_targets', sa.Text(), nullable=True),
    sa.Column('known_associates', sa.JSON(), nullable=True),
    sa.Column('reoffend_probability', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['district_id'], ['districts.district_id'], ),
    sa.PrimaryKeyConstraint('offender_id')
    )
    op.create_index(op.f('ix_offenders_district_id'), 'offenders', ['district_id'], unique=False)
    op.create_index(op.f('ix_offenders_offender_reference'), 'offenders', ['offender_reference'], unique=True)
    op.create_index(op.f('ix_offenders_risk_level'), 'offenders', ['risk_level'], unique=False)
    op.create_index(op.f('ix_offenders_status'), 'offenders', ['status'], unique=False)
    op.create_table('police_stations',
    sa.Column('station_id', sa.String(length=50), nullable=False),
    sa.Column('station_name', sa.String(length=200), nullable=False),
    sa.Column('district_id', sa.String(length=50), nullable=False),
    sa.Column('station_code', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('jurisdiction_area', sa.JSON(), nullable=True),
    sa.Column('officer_in_charge', sa.String(length=200), nullable=True),
    sa.Column('total_officers', sa.Integer(), nullable=True),
    sa.Column('contact_number', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['district_id'], ['districts.district_id'], ),
    sa.PrimaryKeyConstraint('station_id')
    )
    op.create_table('socioeconomic_data',
    sa.Column('data_id', sa.UUID(), nullable=False),
    sa.Column('district_id', sa.String(length=50), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('population_density', sa.Float(), nullable=True),
    sa.Column('unemployment_rate', sa.Float(), nullable=True),
    sa.Column('poverty_index', sa.Float(), nullable=True),
    sa.Column('literacy_rate', sa.Float(), nullable=True),
    sa.Column('urbanization_rate', sa.Float(), nullable=True),
    sa.Column('per_capita_income', sa.Float(), nullable=True),
    sa.Column('young_male_population', sa.Float(), nullable=True),
    sa.Column('drug_cases_count', sa.Integer(), nullable=True),
    sa.Column('alcohol_shops_count', sa.Integer(), nullable=True),
    sa.Column('street_lighting_coverage', sa.Float(), nullable=True),
    sa.Column('cctv_coverage', sa.Float(), nullable=True),
    sa.Column('data_source', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['district_id'], ['districts.district_id'], ),
    sa.PrimaryKeyConstraint('data_id')
    )
    op.create_index(op.f('ix_socioeconomic_data_district_id'), 'socioeconomic_data', ['district_id'], unique=False)
    op.create_table('victims',
    sa.Column('victim_id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('occupation', sa.String(length=200), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('district_id', sa.String(length=50), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('vulnerability_factors', sa.JSON(), nullable=True),
    sa.Column('total_victimizations', sa.Integer(), nullable=True),
    sa.Column('first_victimization', sa.Date(), nullable=True),
    sa.Column('last_victimization', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['district_id'], ['districts.district_id'], ),
    sa.PrimaryKeyConstraint('victim_id')
    )
    op.create_index(op.f('ix_victims_district_id'), 'victims', ['district_id'], unique=False)
    op.create_table('crimes',
    sa.Column('crime_id', sa.UUID(), nullable=False),
    sa.Column('crime_reference_no', sa.String(length=100), nullable=False),
    sa.Column('crime_type', sa.String(length=100), nullable=False),
    sa.Column('crime_sub_type', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date_of_occurrence', sa.Date(), nullable=False),
    sa.Column('time_of_occurrence', sa.String(length=20), nullable=True),
    sa.Column('day_of_week', sa.String(length=20), nullable=True),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('district_id', sa.String(length=50), nullable=False),
    sa.Column('police_station_id', sa.String(length=50), nullable=True),
    sa.Column('location_id', sa.UUID(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('landmark', sa.String(length=300), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('weapons_used', sa.JSON(), nullable=True),
    sa.Column('modus_operandi', sa.Text(), nullable=True),
    sa.Column('property_stolen', sa.String(length=500), nullable=True),
    sa.Column('property_value', sa.Float(), nullable=True),
    sa.Column('reporting_officer_id', sa.UUID(), nullable=True),
    sa.Column('investigating_officer_id', sa.UUID(), nullable=True),
    sa.Column('fir_number', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['district_id'], ['districts.district_id'], ),
    sa.ForeignKeyConstraint(['police_station_id'], ['police_stations.station_id'], ),
    sa.PrimaryKeyConstraint('crime_id')
    )
    op.create_index(op.f('ix_crimes_crime_reference_no'), 'crimes', ['crime_reference_no'], unique=True)
    op.create_index(op.f('ix_crimes_crime_type'), 'crimes', ['crime_type'], unique=False)
    op.create_index(op.f('ix_crimes_date_of_occurrence'), 'crimes', ['date_of_occurrence'], unique=False)
    op.create_index(op.f('ix_crimes_district_id'), 'crimes', ['district_id'], unique=False)
    op.create_index(op.f('ix_crimes_year'), 'crimes', ['year'], unique=False)
    op.create_table('locations',
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('location_name', sa.String(length=300), nullable=False),
    sa.Column('location_type', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('district_id', sa.String(length=50), nullable=True),
    sa.Column('police_station_id', sa.String(length=50), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('total_crimes', sa.Integer(), nullable=True),
    sa.Column('last_crime_date', sa.Date(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('is_hotspot', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['district_id'], ['districts.district_id'], ),
    sa.ForeignKeyConstraint(['police_station_id'], ['police_stations.station_id'], ),
    sa.PrimaryKeyConstraint('location_id')
    )
    op.create_index(op.f('ix_locations_district_id'), 'locations', ['district_id'], unique=False)
    op.create_table('crime_offender_links',
    sa.Column('link_id', sa.UUID(), nullable=False),
    sa.Column('crime_id', sa.UUID(), nullable=False),
    sa.Column('offender_id', sa.UUID(), nullable=False),
    sa.Column('role_in_crime', sa.String(length=50), nullable=True),
    sa.Column('is_confirmed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['crime_id'], ['crimes.crime_id'], ),
    sa.ForeignKeyConstraint(['offender_id'], ['offenders.offender_id'], ),
    sa.PrimaryKeyConstraint('link_id')
    )
    op.create_index(op.f('ix_crime_offender_links_crime_id'), 'crime_offender_links', ['crime_id'], unique=False)
    op.create_index(op.f('ix_crime_offender_links_offender_id'), 'crime_offender_links', ['offender_id'], unique=False)
    op.create_table('crime_victim_links',
    sa.Column('link_id', sa.UUID(), nullable=False),
    sa.Column('crime_id', sa.UUID(), nullable=False),
    sa.Column('victim_id', sa.UUID(), nullable=False),
    sa.Column('injury_level', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['crime_id'], ['crimes.crime_id'], ),
    sa.ForeignKeyConstraint(['victim_id'], ['victims.victim_id'], ),
    sa.PrimaryKeyConstraint('link_id')
    )
    op.create_index(op.f('ix_crime_victim_links_crime_id'), 'crime_victim_links', ['crime_id'], unique=False)
    op.create_index(op.f('ix_crime_victim_links_victim_id'), 'crime_victim_links', ['victim_id'], unique=False)
    op.create_table('evidence',
    sa.Column('evidence_id', sa.UUID(), nullable=False),
    sa.Column('crime_id', sa.UUID(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['crime_id'], ['crimes.crime_id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('evidence_id')
    )
    op.create_index(op.f('ix_evidence_crime_id'), 'evidence', ['crime_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evidence_crime_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_crime_victim_links_victim_id'), table_name='crime_victim_links')
    op.drop_index(op.f('ix_crime_victim_links_crime_id'), table_name='crime_victim_links')
    op.drop_table('crime_victim_links')
    op.drop_index(op.f('ix_crime_offender_links_offender_id'), table_name='crime_offender_links')
    op.drop_index(op.f('ix_crime_offender_links_crime_id'), table_name='crime_offender_links')
    op.drop_table('crime_offender_links')
    op.drop_index(op.f('ix_locations_district_id'), table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_crimes_year'), table_name='crimes')
    op.drop_index(op.f('ix_crimes_district_id'), table_name='crimes')
    op.drop_index(op.f('ix_crimes_date_of_occurrence'), table_name='crimes')
    op.drop_index(op.f('ix_crimes_crime_type'), table_name='crimes')
    op.drop_index(op.f('ix_crimes_crime_reference_no'), table_name='crimes')
    op.drop_table('crimes')
    op.drop_index(op.f('ix_victims_district_id'), table_name='victims')
    op.drop_table('victims')
    op.drop_index(op.f('ix_socioeconomic_data_district_id'), table_name='socioeconomic_data')
    op.drop_table('socioeconomic_data')
    op.drop_table('police_stations')
    op.drop_index(op.f('ix_offenders_status'), table_name='offenders')
    op.drop_index(op.f('ix_offenders_risk_level'), table_name='offenders')
    op.drop_index(op.f('ix_offenders_offender_reference'), table_name='offenders')
    op.drop_index(op.f('ix_offenders_district_id'), table_name='offenders')
    op.drop_table('offenders')
    op.drop_index(op.f('ix_hotspots_district_id'), table_name='hotspots')
    op.drop_table('hotspots')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('system_settings')
    op.drop_table('reports')
    op.drop_index(op.f('ix_predictions_prediction_type'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_district_id'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_table('districts')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_anomalies_status'), table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_severity'), table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_district_id'), table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_anomaly_type'), table_name='anomalies')
    op.drop_table('anomalies')
    op.drop_index(op.f('ix_alerts_severity'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_is_read'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_district_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_alert_type'), table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
